 { 
    	"consultId":"7007575f-cc77-4cdb-81d7-b02dcb916de7",
    	"patientname":"a b",
    	"age":21,
    	"gender":"Male",
    	"patientDob":"05 05 1998",
    	"createdAt":"Thu Dec 12 2019",
    	"currentMedicalIssue":"21",
    	"medical_issues":"21",
    	"medication":"NO",
    	"allergy":"NO",
    	"surgeries":"NO",
    	"plan":"",
    	"impression":"",
    	"impressionDescription":"",
    	"sideEffectsString":"",
    	"skinCareInstructions":"",
    	"url1":{"message":"Missing credentials in config",
    	"code":"CredentialsError",
    	"time":"2019-12-12T10:37:02.058Z",
    	"line":202099,
    	"column":49,
    	"sourceURL":"http://localhost:3000/static/js/0.chunk.js",
    	"originalError":{"message":"No credentials to load",
    	"code":"CredentialsError",
    	"time":"2019-12-12T10:37:02.058Z",
    	"line":202099,
    	"column":49,
    	"sourceURL":"http://localhost:3000/static/js/0.chunk.js"}},
    	"url2":null,
    	"url3":null,
    	"url4":null,
    	"consultDiagnosisData":[{"checkedDiseaseTypes":null,
    	"checkedMedications":null,
    	"diagnosisCannotBeEstablished":null,
    	"diagnosisDescription":null,
    	"diagnosisOption":null,
    	"diseaseGroup":null,
    	"treatmentCannotBeRecommended":null,
    	"treatmentDescription":null,
    	"treatmentOption":null,
    	"impression":"Acne Vulgaris",
    	"plan":"the plan we have..",
    	"impressionDescription":"Acne, also known as acne vulgaris, is thought to be caused by multiple factors. Overproduction of a normal oil on the skin, called sebum, increases under the influence of hormones. This, coupled with insufficient shedding of exfoliating dead skin cells, plugs hair follicles.",
    	"skinCareInstructions":"skin care instructions",
    	"sideEffectsString":"side effect 1",
    	"__typename":"ConsultDiagnosisData"}],
    	"phone_number":"7655360479",
    	"patientAddress":""}